### ISSUE TITLE
Running under @njit

### ISSUE THREAD

**Issue by artiko88** [jcatankard/NumbaML#2]
Hey!

Thank you for this project. Not really an issue that needs to be reported, more of a question. Is there a way i can use methods from the library inside of an @njit decorated functions?

**Comment by jcatankard** [comment]
Hey - thanks for the question! It's a good comment.

You cannot utilise the classes or methods themselves inside @njit decorated functions. But you can use any of this library's @njit decorated functions (that are called by the methods) directly - e.g. importing them directly from fit.py / predict.py / model_selection.py.

This means you don't have the "nice" Python wrappers to make life simpler but you should be able to achieve the same results along with the Numba speed-up. Hope this helps.

**Comment by artiko88** [comment]
Ah, i see! Thank you, will try that!
